### ISSUE TITLE
What is (or was) the workshop schedule?

### ISSUE THREAD

**Issue by MatthiasKauer** [UCIDataScienceInitiative/IntroToJulia#15]
Hi,
I am interested in following this workshop. It is kind of hard to grasp how big this workshop is, however.
You say that

> Not everyone is expected to complete all of the material in the allotted time

but I couldn't find what the "allotted time" actually is or was.

Is or was this a one-day, one-week, one-month workshop?
Or is it entirely online without a clear timeline?

Best regards,
Matthias

**Comment by ChrisRackauckas** [comment]
This was a full day workshop, 9-3. Of the 3 times running it, we never got through all of the materials, and instead after lunch chose what to do based on the interests of the participants.

**Comment by MatthiasKauer** [comment]
Thank you
