### ISSUE TITLE
Advanced Problem: Metaprogramming

### ISSUE THREAD

**Issue by ChrisRackauckas** [UCIDataScienceInitiative/IntroToJulia#19]
@YingboMa do you know of a good metaprogramming problem for teaching?

**Comment by YingboMa** [comment]
I think that we can use the examples from [this discourse thread](https://discourse.julialang.org/t/simple-metaprogramming-exercises-challenges/731). Also, [Cartesian indexing](https://docs.julialang.org/en/stable/devdocs/cartesian/) should also be a great example. It is a quite unique feature in Julia.

**Comment by ChrisRackauckas** [comment]
`@evalpoly` is a good first metaprogramming problem.
