### ISSUE TITLE
More basic problems

### ISSUE THREAD

**Issue by ChrisRackauckas** [UCIDataScienceInitiative/IntroToJulia#20]
@YingboMa @rsulli55 any other data science / scientific computing introduction problems that you like that teach basic language constructs?

One that comes to mind is https://en.wikipedia.org/wiki/Secretary_problem . Need to find some other Project Euler type problems.

**Comment by YingboMa** [comment]
I think [Wilkinson's polynomial](https://en.wikipedia.org/wiki/Wilkinson%27s_polynomial) with perturbations is a great example for demonstrating ill-conditioning in numerical analysis.

**Comment by YingboMa** [comment]
Here is an example.

```julia
using Polynomials, Plots; gr()

srand(1)
function wilkinson_poly_roots(n=100)
    coeff = poly(Int128(1):20).a
    rts = Vector{Complex{Float64}}[]
    # add perturbation
    for i in 1:n
        pert_coeff = coeff.*(1+rand(21)*1e-9)
        push!(rts, roots(Poly(pert_coeff)))
    end
    rts
end
function plt_wilkinson_roots(rts)
    plt = scatter(1:20, zeros(20), color = :green, markersize = 5, legend=false)
    for i in eachindex(rts)
        scatter!(plt, real.(rts[i]), imag.(rts[i]), color = :red, markersize = .5)
    end
    plt
end
wilkinson_poly_roots() |> plt_wilkinson_roots
```
![wilkinson](https://user-images.githubusercontent.com/17304743/39965083-62e545c2-5647-11e8-8e5a-f771f3820dae.png)

**Comment by ChrisRackauckas** [comment]
You use a package here. A basic problem should just be some loops, conditionals, indexing, etc.

**Comment by ChrisRackauckas** [comment]
I filled out some of the topics portions with more basic problems, so that will do.
