### ISSUE TITLE
Where are problems 1-5 ?

### ISSUE THREAD

**Issue by ldesousa** [UCIDataScienceInitiative/IntroToJulia#36]
Midways in the [Introduction page](http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicIntroduction) there is a reference to problems 1-5:

> ## Problems
> Try problems 1-5 in the Basic Problems.

Not sure which is the Basic Problems page,  there is a [Starter Problems page](http://ucidatascienceinitiative.github.io/IntroToJulia/Html/BasicProblems), but it has only four problems, which are not numbered. Also, the Starter Problems page requires the understanding of functions, which are only referenced afterwards in the Introduction.

It might be useful to link from the Introduction page to the actual place where these problems are described.

**Comment by ChrisRackauckas** [comment]
Yeah they were renamed. I need to go through this again and fix it.

**Comment by ChrisRackauckas** [comment]
Fixed in the new notebooks
