### ISSUE TITLE
I can't easily change the notebook...

### ISSUE THREAD

**Issue by sbromberger** [UCIDataScienceInitiative/IntroToJulia#4]
but the solutions notebook has an outdated version of my LG function. The latest is here: https://gist.github.com/sbromberger/74f456619105ac2309d39120fd73bfe9

**Comment by ChrisRackauckas** [comment]
Yeah, that's the issue with notebooks: hard to collaborate. Thanks for the materials though. Although we didn't get there, LG will still be part of the materials and I'll keep them online for people to go through.
