### ISSUE TITLE
Small issues/remark with pdf

### ISSUE THREAD

**Issue by swissr** [UCIDataScienceInitiative/IntroToJulia#7]
Really minor, but I thought I'd mention it in case it's not yet known:
  - DiffEq.pdf is missing (there is a html/slide though)
  - DimentionalityReduction.pdf (likely a typo, there is another newer such pdf (without typo))
  - Untitled.pdf (which is kind of an Interop placeholder, there is a project-Interop.pdf)

Cheers (and, btw, thanks for this great 'quite-deep-intro') !

**Comment by ChrisRackauckas** [comment]
Deleted the extra PDFs. I think DiffEq.pdf is not building because it has images in it. I think that's something the conversion cannot handle. I'll look into this more when I update all of this for in time for the next run of the workshop.
